CREATE TABLE assistant_session (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'assistant session id',
    user_id BIGINT NOT NULL COMMENT 'owner user id',
    title VARCHAR(200) NOT NULL COMMENT 'session title',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'session status: ACTIVE/ARCHIVED',
    pinned TINYINT NOT NULL DEFAULT 0 COMMENT 'whether pinned',
    current_context_type VARCHAR(32) DEFAULT NULL COMMENT 'context type: MATERIAL/QUESTION_SET/PRACTICE_SESSION/AI_TASK',
    current_context_id BIGINT DEFAULT NULL COMMENT 'generic context business id',
    current_material_id BIGINT DEFAULT NULL COMMENT 'bound material id',
    current_question_set_id BIGINT DEFAULT NULL COMMENT 'bound question set id',
    current_practice_session_id BIGINT DEFAULT NULL COMMENT 'bound practice session id',
    last_message_at DATETIME DEFAULT NULL COMMENT 'last message time',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
    CONSTRAINT fk_assistant_session_user FOREIGN KEY (user_id) REFERENCES sys_user (id),
    CONSTRAINT fk_assistant_session_material FOREIGN KEY (current_material_id) REFERENCES study_material (id),
    CONSTRAINT fk_assistant_session_question_set FOREIGN KEY (current_question_set_id) REFERENCES question_set (id),
    CONSTRAINT fk_assistant_session_practice FOREIGN KEY (current_practice_session_id) REFERENCES practice_session (id),
    KEY idx_assistant_session_user_updated (user_id, updated_at),
    KEY idx_assistant_session_user_last_message (user_id, last_message_at),
    KEY idx_assistant_session_context (current_context_type, current_context_id)
) ENGINE = InnoDB COMMENT = 'AI assistant conversation session';

CREATE TABLE assistant_message (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'assistant message id',
    session_id BIGINT NOT NULL COMMENT 'session id',
    user_id BIGINT NOT NULL COMMENT 'owner user id',
    role VARCHAR(20) NOT NULL COMMENT 'message role: USER/ASSISTANT/TOOL/SYSTEM',
    message_type VARCHAR(20) NOT NULL DEFAULT 'TEXT' COMMENT 'message type: TEXT/SUMMARY/PLAN/TOOL_RESULT',
    content_text MEDIUMTEXT NOT NULL COMMENT 'message content',
    reasoning_json LONGTEXT DEFAULT NULL COMMENT 'agent reasoning snapshot json',
    tool_plan_json LONGTEXT DEFAULT NULL COMMENT 'planned tool calls json',
    model_name VARCHAR(100) DEFAULT NULL COMMENT 'reply model name',
    token_input INT DEFAULT NULL COMMENT 'estimated input token count',
    token_output INT DEFAULT NULL COMMENT 'estimated output token count',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
    CONSTRAINT fk_assistant_message_session FOREIGN KEY (session_id) REFERENCES assistant_session (id),
    CONSTRAINT fk_assistant_message_user FOREIGN KEY (user_id) REFERENCES sys_user (id),
    KEY idx_assistant_message_session_created (session_id, created_at),
    KEY idx_assistant_message_user_created (user_id, created_at),
    KEY idx_assistant_message_role (role)
) ENGINE = InnoDB COMMENT = 'AI assistant conversation message';

CREATE TABLE assistant_tool_call (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'assistant tool call id',
    session_id BIGINT NOT NULL COMMENT 'session id',
    message_id BIGINT NOT NULL COMMENT 'trigger message id',
    tool_name VARCHAR(64) NOT NULL COMMENT 'tool name',
    tool_args_json LONGTEXT DEFAULT NULL COMMENT 'tool args json',
    tool_result_json LONGTEXT DEFAULT NULL COMMENT 'tool result json',
    status VARCHAR(20) NOT NULL DEFAULT 'SUCCESS' COMMENT 'tool status: SUCCESS/FAILED/SKIPPED',
    error_message VARCHAR(1000) DEFAULT NULL COMMENT 'tool error message',
    started_at DATETIME DEFAULT NULL COMMENT 'tool start time',
    finished_at DATETIME DEFAULT NULL COMMENT 'tool finish time',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
    CONSTRAINT fk_assistant_tool_call_session FOREIGN KEY (session_id) REFERENCES assistant_session (id),
    CONSTRAINT fk_assistant_tool_call_message FOREIGN KEY (message_id) REFERENCES assistant_message (id),
    KEY idx_assistant_tool_call_session_created (session_id, created_at),
    KEY idx_assistant_tool_call_message (message_id),
    KEY idx_assistant_tool_call_name_status (tool_name, status)
) ENGINE = InnoDB COMMENT = 'AI assistant tool execution record';

CREATE TABLE assistant_memory (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'assistant memory id',
    user_id BIGINT NOT NULL COMMENT 'owner user id',
    memory_scope VARCHAR(32) NOT NULL COMMENT 'memory scope: PROFILE/GOAL/PREFERENCE/WEAKNESS/PROGRESS/CONTEXT',
    memory_type VARCHAR(32) NOT NULL COMMENT 'memory type',
    topic_name VARCHAR(200) DEFAULT NULL COMMENT 'memory topic',
    content_text MEDIUMTEXT NOT NULL COMMENT 'memory content',
    summary_text VARCHAR(500) DEFAULT NULL COMMENT 'memory summary',
    source_type VARCHAR(32) DEFAULT NULL COMMENT 'source type',
    source_id BIGINT DEFAULT NULL COMMENT 'source business id',
    importance_score DECIMAL(5,2) NOT NULL DEFAULT 0.00 COMMENT 'importance score 0-100',
    confidence_score DECIMAL(5,2) NOT NULL DEFAULT 0.00 COMMENT 'confidence score 0-100',
    hit_count INT NOT NULL DEFAULT 0 COMMENT 'retrieval hit count',
    last_hit_at DATETIME DEFAULT NULL COMMENT 'last hit time',
    vector_status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT 'vector status: PENDING/SUCCESS/FAILED',
    embedding_model VARCHAR(100) DEFAULT NULL COMMENT 'embedding model name',
    embedding_task_id BIGINT DEFAULT NULL COMMENT 'embedding task id',
    vector_id VARCHAR(128) DEFAULT NULL COMMENT 'vector store point id',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
    CONSTRAINT fk_assistant_memory_user FOREIGN KEY (user_id) REFERENCES sys_user (id),
    KEY idx_assistant_memory_user_scope (user_id, memory_scope),
    KEY idx_assistant_memory_user_type (user_id, memory_type),
    KEY idx_assistant_memory_source (source_type, source_id),
    KEY idx_assistant_memory_hit (user_id, last_hit_at),
    KEY idx_assistant_memory_vector (vector_status, embedding_task_id)
) ENGINE = InnoDB COMMENT = 'AI assistant structured memory';
